//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodeAbp.Scaffolding {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodeAbp.Scaffolding.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 不需要描述了 的本地化字符串。
        /// </summary>
        internal static string MVCScaffolder_Description {
            get {
                return ResourceManager.GetString("MVCScaffolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不需要描述 的本地化字符串。
        /// </summary>
        internal static string MVCScaffolder_Description2 {
            get {
                return ResourceManager.GetString("MVCScaffolder_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成MVC5增删改查 的本地化字符串。
        /// </summary>
        internal static string MVCScaffolder_Name {
            get {
                return ResourceManager.GetString("MVCScaffolder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成列表查询 的本地化字符串。
        /// </summary>
        internal static string MVCScaffolder_Name2 {
            get {
                return ResourceManager.GetString("MVCScaffolder_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新的data context... 的本地化字符串。
        /// </summary>
        internal static string WebFormsCodeGeneratorViewModel_AddNewDbContext {
            get {
                return ResourceManager.GetString("WebFormsCodeGeneratorViewModel_AddNewDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能加载的Model类型。如果项目没有编译，请编译后重试。 的本地化字符串。
        /// </summary>
        internal static string WebFormsScaffolder_ProjectNotBuilt {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_ProjectNotBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个有效的 DbContext 类。 的本地化字符串。
        /// </summary>
        internal static string WebFormsScaffolder_SelectDbContextType {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_SelectDbContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个有效的 Model 类。 的本地化字符串。
        /// </summary>
        internal static string WebFormsScaffolder_SelectModelType {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_SelectModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要先调用ShowUIAndValidate方法。 的本地化字符串。
        /// </summary>
        internal static string WebFormsScaffolder_ShowUIAndValidateNotCalled {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_ShowUIAndValidateNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action名称不可为空 的本地化字符串。
        /// </summary>
        internal static string WebFormsViewScaffolder_EmptyActionName {
            get {
                return ResourceManager.GetString("WebFormsViewScaffolder_EmptyActionName", resourceCulture);
            }
        }
    }
}
